### ISSUE TITLE
Better ways to orchestrate vLLM workloads using RayClusterFleet

### ISSUE THREAD

**Issue by Jeffwan** [vllm-project/aibrix#245]
### 🚀 Feature Description and Motivation

```
                command: ["/bin/bash", "-lc", "--"]
                # Starting from v1.1.0, KubeRay injects the environment variable `KUBERAY_GEN_RAY_START_CMD`
                # into the Ray container. This variable can be used to retrieve the generated Ray start command.
                # Note that this environment variable does not include the `ulimit` command.
                args: ["ulimit -n 65536; echo head; ray start --head --num-cpus=1 --num-gpus=1 --dashboard-host=0.0.0.0 --metrics-export-port=8080 --dashboard-agent-listen-port=52365; sleep 60; vllm serve /models/llama-2-7b-hf/ --served-model-name meta-llama/llama-2-7b-hf"]
```

We use such way to launch vLLM using `RayClusterFleet` api, there're two blocker issues. 
1. https://github.com/aibrix/aibrix/issues/243 after this is resolved, we can at least use `KUBERAY_GEN_RAY_START_CMD` to replace the ray startup scripts
2. the time application starts, the ray worker node may not join the cluster yet. so application will encounter some issues like https://github.com/aibrix/aibrix/issues/228

The workaround now is to use `sleep 60` before we launch application scripts. There's no guarantee actually. Let's see if there's a way to better orchestrate this workload with limited changes.

### Proposed Solution

KubeRay injects the resource information and I am thinking it's possible to inject some resource ready checks in the ray cluster commands so we can use. This could be a feature flag in KubeRay

**Comment by SongGuyang** [comment]
@Yicheng-Lu-llll will you send a PR of this commit [branch](https://github.com/ray-project/kuberay/commit/91e1c26fbf1fc0f505ff7d16b70cf8228ed62ec4#diff-cc9abb27aaceca3f10193e2ab35fb00dca44b8858709c5c0f4df751c1387291aR576) to the kuberay main branch?

**Comment by Yicheng-Lu-llll** [comment]
> [@Yicheng-Lu-llll](https://github.com/Yicheng-Lu-llll) will you send a PR of this commit [branch](https://github.com/ray-project/kuberay/commit/91e1c26fbf1fc0f505ff7d16b70cf8228ed62ec4#diff-cc9abb27aaceca3f10193e2ab35fb00dca44b8858709c5c0f4df751c1387291aR576) to the kuberay main branch?

Sure, let me sync with @kevin85421 and get his opinion first.

**Comment by kevin85421** [comment]
I will chat with @Yicheng-Lu-llll next week.

**Comment by Yicheng-Lu-llll** [comment]
Synced with @kevin85421. We could do two things for this issue:

1. Add a placement group wait timeout to VLLM so that it doesn't immediately fail if Ray workers haven't joined yet.

2. For Ray, add a CLI command to wait until all workers have joined.

**Comment by kevin85421** [comment]
https://github.com/ray-project/ray/issues/51860
